language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t rohitrainbow/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true rohitrainbow/docker-react npm run test -- --coverage